plugins:
  - jekyll-feed
  - jekyll-paginate

jira_url:    https://osgeo-org.atlassian.net/projects/GEOS
wiki_url:    https://github.com/geoserver/geoserver/wiki
git_url:     https://github.com/geoserver/geoserver
sf_url:      https://sourceforge.net/projects/geoserver
nightly_url: https://build.geoserver.org/geoserver
docs_url:    https://docs.geoserver.org

# stable latest release
stable_version:   2.20.3

# stable nightly build
stable_branch:    2.20.x
stable_jira:      16842

# maintenance latest release
maintain_version: 2.19.5

# maintenance nightly build
maintain_branch:  2.19.x
maintain_jira:    16843

# release candidate if available 
dev_version:      
dev_branch:       main
dev_jira:         
dev_series:       2.21.x

# latest
main_jira:        16829
main_series:      2.21.x


timezone:    UTC
name:        GeoServer
description: GeoServer latest posts
author:      GeoServer community

paginate: 5
paginate_path: "/blog/page:num/"
