plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap

jira_url:    https://osgeo-org.atlassian.net/projects/GEOS
wiki_url:    https://github.com/geoserver/geoserver/wiki
git_url:     https://github.com/geoserver/geoserver
sf_url:      https://sourceforge.net/projects/geoserver
nightly_url: https://build.geoserver.org/geoserver
docs_url:    https://docs.geoserver.org
url:         https://geoserver.org

# stable      (determine nightly build, stable_version)
stable_branch:    2.23.x

# the next jira release for the stable branch
stable_jira:      16888

# maintenance (determine nightly build, maintain_version)
maintain_branch:  2.22.x

# the next jira release for the maintenance branch
maintain_jira:    16882

# release candidate if available 
# dev         (determine dev_version)
dev_branch:       main
dev_series:       2.24.x

# latest nightly build
main_series:      2.24.x

# the next jira release for the main branch
main_jira:        16884

timezone:    UTC
name:        GeoServer
description: GeoServer latest posts
author:      GeoServer community

paginate: 5
paginate_path: "/blog/page:num/"

defaults:
  -
    scope:
      path:       "img/**"
    values:
      sitemap:    false
  -
    scope:
      path:       "google0de0c8ffb164bba6.html"
    values:
      sitemap:    false
