plugins:
  - jekyll-feed

jira_url:    https://osgeo-org.atlassian.net/projects/GEOS
wiki_url:    https://github.com/geoserver/geoserver/wiki
git_url:     https://github.com/geoserver/geoserver
sf_url:      http://sourceforge.net/projects/geoserver
nightly_url: https://build.geoserver.org/geoserver
docs_url:    http://docs.geoserver.org

stable_version:   2.19.1
stable_jira:      16821
stable_branch:    2.19.x
maintain_version: 2.18.3
maintain_jira:    16819
maintain_branch:  2.18.x
dev_version:      
dev_branch:       main
dev_jira:         16815
dev_series:       2.20.x

timezone:    UTC
name:        GeoServer
description: GeoServer latest posts
author:      GeoServer community
