jira_url: https://osgeo-org.atlassian.net/projects/GEOS
wiki_url: https://github.com/geoserver/geoserver/wiki
git_url: https://github.com/geoserver/geoserver
sf_url: http://sourceforge.net/projects/geoserver
nightly_url: https://build.geoserver.org/geoserver
docs_url: http://docs.geoserver.org

stable_version: 2.16.2
stable_branch: 2.16.x
maintain_version: 2.15.5
maintain_branch: 2.15.x
dev_version: 2.17-RC
dev_branch: master

timezone: UTC
