plugins:
  - jekyll-feed
  - jekyll-paginate

jira_url:    https://osgeo-org.atlassian.net/projects/GEOS
wiki_url:    https://github.com/geoserver/geoserver/wiki
git_url:     https://github.com/geoserver/geoserver
sf_url:      https://sourceforge.net/projects/geoserver
nightly_url: https://build.geoserver.org/geoserver
docs_url:    https://docs.geoserver.org

# stable      (determine nightly build, stable_version)
stable_branch:    2.21.x

# the next jira release for the stable branch
stable_jira:      16844

# maintenance (determine nightly build, maintain_version)
maintain_branch:  2.20.x

# the next jira release for the maintenance branch
maintain_jira:    16845

# release candidate if available 
# dev         (determine dev_version)
dev_branch:       2.22.x
dev_series:       2.22.x

# latest nightly build
main_series:      2.22.x

# the next jira release for the main branch
main_jira:        16854

timezone:    UTC
name:        GeoServer
description: GeoServer latest posts
author:      GeoServer community

paginate: 5
paginate_path: "/blog/page:num/"
